jobs:
- deployment: DeployInfra
  displayName: Deploy Azure Infra
  pool:
    vmImage: 'windows-latest'
  environment: 'mirror'
  strategy: 
    runOnce:
      preDeploy:
        steps:
        - checkout: self
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on miferrac-mirror'
          inputs:
            azureSubscription: 'PFE 500 (fd94b044-d980-40d3-bd9c-0417736c7b36)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'miferrac-mirror'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(System.DefaultWorkingDirectory)/_phenixita_traffic-manager-demo/infra/azure/webapp/template.json'
            csmParametersFile: '$(System.DefaultWorkingDirectory)/_phenixita_traffic-manager-demo/infra/azure/webapp/parameters.json'
            deploymentMode: 'Incremental'
      deploy:
        steps:
          - script: 'echo deploy steps'
      routeTraffic:
        steps:
          - script: 'echo routeTraffic steps'
      postRouteTraffic:
        steps:
          - script: 'echo postRouteTraffic steps'
      on:
        failure:
          steps:
          - script: 'echo on failure steps'
        success:
          steps:
          - script: 'echo on success steps'