jobs:
- deployment: DeployInfra
  displayName: Deploy Azure Infra
  pool:
    vmImage: 'Ubuntu-16.04'
  environment: 'mirror'
  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'PFE 500 (fd94b044-d980-40d3-bd9c-0417736c7b36)'
            subscriptionId: 'fd94b044-d980-40d3-bd9c-0417736c7b36'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'nd-mirroring'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            deploymentMode: 'Incremental'
 