jobs:
- deployment: DeployInfra
  displayName: Deploy Azure Infra
  pool:
    vmImage: 'windows-latest'
  environment: 'mirror'
  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: AzureResourceManagerTemplateDeployment@3
          enabled: true
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'vse miferrac'
            subscriptionId: 'dce4a55c-1d65-46ec-bd2b-831801fc6bab'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'miferrac-mirror'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/azure/webapp/template.json'
            csmParametersFile: 'infra/azure/webapp/parameters.json'
            deploymentMode: 'Incremental'
            deploymentName: 'deployment-azdo-$(build.buildnumber)'